---
title: "Home Lab"
subtitle: "Welcome to"
#logo: "logo.png"
icon: "fas fa-hexagon-nodes" 

header: true
footer:  'Have fun while at it.' # Set false if you want to hide it.

stylesheet:
   - "assets/custom.css"

# You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
columns: "4"

# Optional theme customization
theme: default

# Optional theme customization (color overrrides)
# overrrides can also be done using CSS vars 
colors:
  light:
    highlight-primary: "#21183A45"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#28334e"
    background-color: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fff"
    text-title: "#fff"
    text-subtitle: "#AEDBDF"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"

  dark:
    highlight-primary: "#21183A45"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#1d273d"
    card-background: rgba(40, 87, 176, 0.8)
    text: "#eaeaea"
    text-header: "#d9d9d9"
    text-title: "#B9B4C7"
    text-subtitle: "#9290C3"
    card-shadow: rgba(42, 68, 138, 1)
    link: "#c1c1c1"
    link-hover: "#fafafa"


# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Cloudflare"
    icon: "fab fa-cloudflare"
    url: "https://dash.cloudflare.com/login"
    target: "_blank" 

  - name: "Docker Hub"
    icon: "fab fa-docker"
    url: "https://hub.docker.com/"
    target: "_blank"

  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/"
    target: "_blank"

  - name: "M-Lab's Speed Test"
    icon: "fas fa-solid fa-gauge"
    url: "https://speed.measurementlab.net/"
    target: "_blank"

  - name: "Site Manager"
    icon: "fa-solid fa-bars-progress"
    url: "https://unifi.ui.com/"    
    target: "_blank" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).

services:
  - name: "Server"
    icon: "fas fa-cogs"
    items:
      - name: "Xodus"
        logo: "assets/logo/proxmox.png"
        subtitle: "Virtual Environment"
        tag: "server"
        url: "https://192.168.0.1:8000"
        target: "_blank" 
        node: "Xodus"

     
      - name: "Mediaverse"
        logo: "assets/logo/proxmox.png"
        subtitle: "Virtual Environment"
        tag: "server"
        url: "https://192.168.0.1:8000"
        target: "_blank"
        
      - name: "Portainer"
        logo: "assets/logo/portainer.png"
        subtitle: "GUI for Docker."
        tag: "server"
        url: "https://192.168.0.1:8000"
        target: "_blank"
        
      - name: "TrueNAS"
        logo: "assets/logo/truenas.png"
        subtitle: NAS Server."
        tag: "server"
        url: "https://192.168.0.1:8000"
        target: "_blank"         
        
  - name: "Network"
    icon: "fas fa-network-wired"
    items:
      - name: "Adguard"
        logo: "assets/logo/adguard.png"
        subtitle: "Network AD blocker."
        tag: "network"
        url: "https://192.168.0.1:8000"
        target: "_blank"

      - name: "IPMI"
        logo: "assets/logo/ipmi.png"
        subtitle: "NAS Mgt Console."
        tag: "network"
        url: "https://192.168.0.1:8000"
        target: "_blank"

      - name: "Nginx Proxy Manager"
        logo: "assets/logo/npm.png"
        subtitle: "Proxy Manager."
        tag: "network"
        url: "https://192.168.0.1:8000"
        target: "_blank"   
        
      - name: "Unifi"
        logo: "assets/logo/unifi.png"
        subtitle: "Router and Firewall."
        tag: "network"
        url: "http://192.168.0.1"
        target: "_blank"         
        
      - name: "Uptime Kuma"
        logo: "assets/logo/uptimekuma.png"
        subtitle: "Monitoring Tool."
        tag: "network"
        url: "https://192.168.0.1:8000"
        target: "_blank"  
        
  - name: "Media"
    icon: "fas fa-television"
    items:
      - name: "Emby"
        logo: "assets/logo/emby.png"
        subtitle: "Movies and TV Series."
        tag: "media"
        url: "https://192.168.0.1:8000"
        target: "_blank"

      - name: "Jellyfin"
        logo: "assets/logo/jellyfin.png"
        subtitle: "Movies and TV Series."
        tag: "media"
        url: "https://192.168.0.1:8000"
        target: "_blank"
        
      - name: "Navidrome"
        logo: "assets/logo/navidrome.png"
        subtitle: "Music Streaming Server"
        tag: "media"
        url: "https://192.168.0.1:8000"
        target: "_blank"
        
      - name: "Plex"
        logo: "assets/logo/plex.png"
        subtitle: "Movies, TV Series and Music."
        tag: "media"
        url: "https://192.168.0.1:8000"
        target: "_blank"
        
  - name: "Tools"
    icon: "fas fa-wrench"
    items:
      - name: "Glance"
        logo: "assets/logo/firefly.png"
        subtitle: "Feeds Dashboard."
        tag: "tools"
        url: "https://192.168.0.1:8000"
        target: "_blank" 

      - name: "Home Assistant"
        logo: "assets/logo/homeassistant.png"
        subtitle: "Smart Home Dashboard."
        tag: "tools"
        url: "https://192.168.0.1:8000"
        target: "_blank"

      - name: "Ntfy"
        logo: "assets/logo/ntfy.png"
        subtitle: "Push Notification."
        tag: "tools"
        url: "https://192.168.0.1:8000"
        target: "_blank"  

      - name: "Nextcloud"
        logo: "assets/logo/nextcloud.png"
        subtitle: "File Storage Cloud."
        tag: "tools"
        url: "https://192.168.0.1:8000"
        target: "_blank"        
      
      - name: "Vaultwarden"
        logo: "assets/logo/vaultwarden.png"
        subtitle: "Password Manager."
        tag: "tools"
        url: "https://192.168.0.1:8000"
        target: "_blank"  
        